package fi.wsnusbcollect.messages;

/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TimeSyncMsg'
 * message type.
 */

public class TimeSyncMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 10;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 234;

    /** Create a new TimeSyncMsg of size 10. */
    public TimeSyncMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TimeSyncMsg of the given data_length. */
    public TimeSyncMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TimeSyncMsg with the given data_length
     * and base offset.
     */
    public TimeSyncMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TimeSyncMsg using the given byte array
     * as backing store.
     */
    public TimeSyncMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TimeSyncMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TimeSyncMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TimeSyncMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TimeSyncMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TimeSyncMsg embedded in the given message
     * at the given base offset.
     */
    public TimeSyncMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TimeSyncMsg embedded in the given message
     * at the given base offset and length.
     */
    public TimeSyncMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TimeSyncMsg> \n";
      try {
        s += "  [counter=0x"+Long.toHexString(get_counter())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [high=0x"+Long.toHexString(get_high())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [low=0x"+Long.toHexString(get_low())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [flags=0x"+Long.toHexString(get_flags())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: counter
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'counter' is signed (false).
     */
    public static boolean isSigned_counter() {
        return false;
    }

    /**
     * Return whether the field 'counter' is an array (false).
     */
    public static boolean isArray_counter() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'counter'
     */
    public static int offset_counter() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'counter'
     */
    public static int offsetBits_counter() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'counter'
     */
    public short get_counter() {
        return (short)getUIntBEElement(offsetBits_counter(), 8);
    }

    /**
     * Set the value of the field 'counter'
     */
    public void set_counter(short value) {
        setUIntBEElement(offsetBits_counter(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'counter'
     */
    public static int size_counter() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'counter'
     */
    public static int sizeBits_counter() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: high
    //   Field type: long, unsigned
    //   Offset (bits): 8
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'high' is signed (false).
     */
    public static boolean isSigned_high() {
        return false;
    }

    /**
     * Return whether the field 'high' is an array (false).
     */
    public static boolean isArray_high() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'high'
     */
    public static int offset_high() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'high'
     */
    public static int offsetBits_high() {
        return 8;
    }

    /**
     * Return the value (as a long) of the field 'high'
     */
    public long get_high() {
        return (long)getUIntBEElement(offsetBits_high(), 32);
    }

    /**
     * Set the value of the field 'high'
     */
    public void set_high(long value) {
        setUIntBEElement(offsetBits_high(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'high'
     */
    public static int size_high() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'high'
     */
    public static int sizeBits_high() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: low
    //   Field type: long, unsigned
    //   Offset (bits): 40
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'low' is signed (false).
     */
    public static boolean isSigned_low() {
        return false;
    }

    /**
     * Return whether the field 'low' is an array (false).
     */
    public static boolean isArray_low() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'low'
     */
    public static int offset_low() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'low'
     */
    public static int offsetBits_low() {
        return 40;
    }

    /**
     * Return the value (as a long) of the field 'low'
     */
    public long get_low() {
        return (long)getUIntBEElement(offsetBits_low(), 32);
    }

    /**
     * Set the value of the field 'low'
     */
    public void set_low(long value) {
        setUIntBEElement(offsetBits_low(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'low'
     */
    public static int size_low() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'low'
     */
    public static int sizeBits_low() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: flags
    //   Field type: short, unsigned
    //   Offset (bits): 72
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'flags' is signed (false).
     */
    public static boolean isSigned_flags() {
        return false;
    }

    /**
     * Return whether the field 'flags' is an array (false).
     */
    public static boolean isArray_flags() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'flags'
     */
    public static int offset_flags() {
        return (72 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'flags'
     */
    public static int offsetBits_flags() {
        return 72;
    }

    /**
     * Return the value (as a short) of the field 'flags'
     */
    public short get_flags() {
        return (short)getUIntBEElement(offsetBits_flags(), 8);
    }

    /**
     * Set the value of the field 'flags'
     */
    public void set_flags(short value) {
        setUIntBEElement(offsetBits_flags(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'flags'
     */
    public static int size_flags() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'flags'
     */
    public static int sizeBits_flags() {
        return 8;
    }

}
