#!/bin/bash

# get current directory 
DIR="$( cd -P "$( dirname "$0" )" && pwd )"; 

java -cp ${DIR}/target/dependencies/javacsv-2.0.jar:${DIR}/target/dependencies/activation-1.1.jar:${DIR}/target/dependencies/ini4j-0.5.2.jar:${DIR}/target/dependencies/spring-aspects-3.1.1.RELEASE.jar:${DIR}/target/dependencies/antlr-2.7.7.jar:${DIR}/target/dependencies/javassist-3.15.0-GA.jar:${DIR}/target/dependencies/spring-beans-3.1.1.RELEASE.jar:${DIR}/target/dependencies/aopalliance-1.0.jar:${DIR}/target/dependencies/jboss-logging-3.1.0.CR2.jar:${DIR}/target/dependencies/spring-context-3.1.1.RELEASE.jar:${DIR}/target/dependencies/args4j-2.0.16.jar:${DIR}/target/dependencies/jboss-transaction-api_1.1_spec-1.0.0.Final.jar:${DIR}/target/dependencies/spring-context-support-3.1.1.RELEASE.jar:${DIR}/target/dependencies/asm-3.1.jar:${DIR}/target/dependencies/jcl-over-slf4j-1.5.11.jar:${DIR}/target/dependencies/spring-core-3.1.1.RELEASE.jar:${DIR}/target/dependencies/aspectjrt-1.7.0.BUILD-20111110.160547-2.jar:${DIR}/target/dependencies/jms-1.1.jar:${DIR}/target/dependencies/spring-expression-3.1.1.RELEASE.jar:${DIR}/target/dependencies/aspectjtools-1.7.0.BUILD-20111110.160547-1.jar:${DIR}/target/dependencies/jul-to-slf4j-1.5.11.jar:${DIR}/target/dependencies/spring-instrument-3.1.1.RELEASE.jar:${DIR}/target/dependencies/aspectjweaver-1.7.0.BUILD-20111110.160547-1.jar:${DIR}/target/dependencies/junit-3.8.1.jar:${DIR}/target/dependencies/spring-jdbc-3.1.1.RELEASE.jar:${DIR}/target/dependencies/c3p0-0.9.1.jar:${DIR}/target/dependencies/jython-2.5.3b1.jar:${DIR}/target/dependencies/spring-orm-3.1.1.RELEASE.jar:${DIR}/target/dependencies/cglib-2.2.jar:${DIR}/target/dependencies/log4j-1.2.15.jar:${DIR}/target/dependencies/spring-test-3.1.1.RELEASE.jar:${DIR}/target/dependencies/commons-collections-3.2.1.jar:${DIR}/target/dependencies/mail-1.4.jar:${DIR}/target/dependencies/spring-tx-3.1.1.RELEASE.jar:${DIR}/target/dependencies/dom4j-1.6.1.jar:${DIR}/target/dependencies/mysql-connector-java-5.1.18.jar:${DIR}/target/dependencies/tinyos-2.1.jar:${DIR}/target/dependencies/hibernate-c3p0-4.1.0.Final.jar:${DIR}/target/dependencies/slf4j-api-1.5.11.jar:${DIR}/target/dependencies/xml-apis-1.0.b2.jar:${DIR}/target/dependencies/hibernate-commons-annotations-4.0.1.Final.jar:${DIR}/target/dependencies/slf4j-log4j12-1.5.11.jar:${DIR}/target/dependencies/xmlpull-1.1.3.1.jar:${DIR}/target/dependencies/hibernate-core-4.1.0.Final.jar:${DIR}/target/dependencies/spring-agent-2.5.6.jar:${DIR}/target/dependencies/xpp3_min-1.1.4c.jar:${DIR}/target/dependencies/hibernate-entitymanager-4.1.0.Final.jar:${DIR}/target/dependencies/spring-aop-3.1.1.RELEASE.jar:${DIR}/target/dependencies/xstream-1.4.2.jar:${DIR}/target/dependencies/hibernate-jpa-2.0-api-1.0.1.Final.jar:${DIR}/target/dependencies/spring-asm-3.1.1.RELEASE.jar:${DIR}/target/original-WsnUSBCollect-1.0-SNAPSHOT.jar \
-Djava.security.policy=${DIR}/server.policy \
-Djava.rmi.server.codebase=file:${DIR}/target/original-WsnUSBCollect-1.0-SNAPSHOT.jar  \
-Djava.rmi.server.hostname=127.0.0.1 \
fi.wsnusbcollect.SenslabForwarder $*
